### PR TITLE
Add course exercise example notebook

### PR DESCRIPTION
**Pull request by michuschenk**
**Includes**
 - Example Jupyter notebook with some exercises for the accelerator course
 - Minor modifications to the Beam class (added particle mass, relativistic beta and gamma, as well as a matched particle initialization method required for the exercise)

### CODE REVIEW

**Comment by michuschenk** [comment]
There is also a small function to slice up all the Drift elements into many smaller drifts. This helps getting nicer results for the beta-functions in the course exercises, for example. Probably this small function could / should be included in the accelerator tools.

**Comment by loiccoyle** [comment]
Hi Michael,

I had a look at the notebook and it looks really cool, well done !

I'll add the slicing method to the toolbox. 

I saw that tracking a distribution of particles is tedious, I originaly wanted to to have a nice way of doing this which is why I added the sampling functions but I never got around to it. I'll think about a nice way of doing it. If you have any suggestions I'm all ears.

> Would be nice to implement a function that can plot the lattice and add labels / indices which index in the phase_space array corresponds to which location in the lattice

By this you mean something like the unused plot you left at the end but with the element names or indices in the lattice object ?

**Comment by michuschenk** [comment]
Hi Loic!

It was a lot of fun to work with your toolbox, it’s really great for our purposes of the course (and quite possibly also for other stuff!)

Thanks for adding the slicing method!

Indeed the tracking of a distribution would be really nice to have to simplify everything “on the surface”. You saw my solution in the notebook, not very inspiring. So for the tracking itself I didn’t have a better idea yet :( What’s important certainly for the sampling (I thought you had maybe intended to do that already) is to have the distribution matched to the Twiss where you start tracking, ie. where you “inject” beam. It’s maybe not too bad to have that done explicitly and not automatic.

For the last point: yes exactly! But again, didn’t have a good idea to do it in a neat way so didn’t want to mess up your code that’s why the function is left separate. I mean adding the labels would not be difficult, but maybe you have a better idea how to implement the whole thing. I was thinking you need some kind of mapping of magnet type -> linestyle surely, I think that’s what’s left. Just wasn't very happy with it and didn't have more time to extend and improve.

**Comment by loiccoyle** [comment]
Ok understood, I'll merge this and have a think about the rest!

BTW I sent you a collaborator invite so you should be able to interact with the repo directly if you want.

**Pull request merged**
